name: Build and deploy

on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  buildAndDeploy:
    name: "Job: Build and deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java:
          - 8
        scala:
          - 2_12
    steps:
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            java-version: ${{matrix.java}}
            distribution: adopt
        - uses: coursier/cache-action@v6
        - run: sbt "SetScala${{ matrix.scala }}" publish
